const motives = [
        "Focus on your goals, the noise doesn't matter. Go for GLORY!",
        "Doubt kills more dreams than failure ever will.",
        "Success is a habit, not an act. Keep practicing!",
        "Consistency is more important than intensity.",
        "Every MCQ brings you closer to your Dream University.",
        "Master the fundamentals, and success will follow."
    ];

    const quizData = {
        "Set 1": { pass: "1234", msg: motives[0], questions: [
            // COMPUTER SCIENCE (1-40)
 
  { "q": "In Banker's Algorithm, which state ensures that all processes can finish execution without a deadlock?", o: ["A) Blocked State", "B) Safe State", "C) Unsafe State", "D) Critical State"], "a": 1 },
  { "q": "What is the maximum number of nodes in a binary tree of height 'k' (where root is at height 1)?", o: ["A) 2^k", "B) 2^k - 1", "C) 2^(k-1)", "D) 2k - 1"], "a": 1 },
  { "q": "Which flip-flop is known as a 'Delay Flip-Flop' because it delays the input to the output by one clock pulse?", o: ["A) JK Flip-Flop", "B) T Flip-Flop", "C) D Flip-Flop", "D) SR Flip-Flop"], "a": 2 },
  { "q": "If a process is waiting for an I/O operation to complete, it is in which state?", o: ["A) Ready State", "B) Running State", "C) Terminated State", "D) Waiting/Blocked State"], "a": 3 },
  { "q": "Which sorting algorithm is 'Stable' and has a worst-case time complexity of O(n log n)?", o: ["A) Quick Sort", "B) Heap Sort", "C) Merge Sort", "D) Selection Sort"], "a": 2 },
  { "q": "How many select lines are required for a 32-to-1 Multiplexer?", o: ["A) 4", "B) 5", "C) 6", "D) 32"], "a": 1 },
  { "q": "Which page replacement algorithm suffers from Belady's Anomaly?", o: ["A) LRU", "B) Optimal", "C) FIFO", "D) MRU"], "a": 2 },
  { "q": "In a Max-Heap, where is the smallest element always located?", o: ["A) Root Node", "B) A Leaf Node", "C) Left Child of Root", "D) Right Child of Root"], "a": 1 },
  { "q": "What is the 2's complement of the binary number 101100?", o: ["A) 010011", "B) 010100", "C) 110011", "D) 010101"], "a": 1 },
  { "q": "Which data structure is most suitable for performing Level Order Traversal of a tree?", o: ["A) Stack", "B) Priority Queue", "C) Deque", "D) Queue"], "a": 3 },
  
  { "q": "Which disk scheduling algorithm services requests in the direction of head movement until it reaches the end?", o: ["A) SSTF", "B) SCAN", "C) C-LOOK", "D) FCFS"], "a": 1 },
  { "q": "In a B-Tree of order 'm', every node except the root can have at most how many children?", o: ["A) m/2", "B) m-1", "C) m", "D) 2m"], "a": 2 },
  { "q": "The Boolean expression A + A'B is equivalent to which of the following?", o: ["A) A + B", "B) A", "C) AB", "D) B"], "a": 0 },
  { "q": "Which of the following is NOT a necessary condition for a deadlock to occur?", o: ["A) Mutual Exclusion", "B) No Preemption", "C) Circular Wait", "D) Process Preemption"], "a": 3 },
  { "q": "What is the time complexity to find the shortest path between all pairs of vertices in a graph using Floyd-Warshall?", o: ["A) O(V^2)", "B) O(V^3)", "C) O(E log V)", "D) O(V+E)"], "a": 1 },
  { "q": "A memory management scheme that allows the physical address space of a process to be non-contiguous is?", o: ["A) Fragmentation", "B) Paging", "C) Swapping", "D) Compaction"], "a": 1 },
  { "q": "Which gate is known as the 'Universal Gate'?", o: ["A) AND", "B) OR", "C) NAND", "D) XOR"], "a": 2 },
  { "q": "The number of edges in a complete graph with 'n' vertices is:", o: ["A) n(n-1)", "B) n(n-1)/2", "C) n^2", "D) 2n-1"], "a": 1 },
  { "q": "In an 8085 microprocessor, the 'Stack Pointer' is a:", o: ["A) 8-bit Register", "B) 16-bit Register", "C) 32-bit Register", "D) 4-bit Register"], "a": 1 },
  { "q": "Which traversal of a Binary Search Tree (BST) produces the elements in sorted order?", o: ["A) Pre-order", "B) Post-order", "C) In-order", "D) Level-order"], "a": 2 }  
        ] },
      
        "Set 2": { pass: "1234", msg: motives[1], questions: [

         // COMPUTER SCIENCE (1-40)
           
  { "q": "What is the phenomenon called where the system spends more time paging than executing processes?", o: ["A) Fragmentation", "B) Paging", "C) Thrashing", "D) Spooling"], "a": 2 },
  { "q": "In a Red-Black Tree, the root node is always of which color?", o: ["A) Red", "B) Black", "C) Green", "D) Any Color"], "a": 1 },
  { "q": "Which register holds the address of the next instruction to be fetched from memory?", o: ["A) Accumulator", "B) Instruction Register", "C) Program Counter", "D) Memory Data Register"], "a": 2 },
  { "q": "A Binary Search Tree is generated by inserting 7, 5, 1, 8, 3, 6, 0 in order. What is the height of the tree?", o: ["A) 3", "B) 4", "C) 5", "D) 6"], "a": 0 },
  { "q": "How many cells are there in a 4-variable Karnaugh Map (K-Map)?", o: ["A) 4", "B) 8", "C) 16", "D) 32"], "a": 2 },
  { "q": "Which data structure is most efficient to find the 'Minimum Spanning Tree' using Prim's Algorithm?", o: ["A) Stack", "B) Deque", "C) Priority Queue", "D) Circular Queue"], "a": 2 },
  { "q": "The 'Wait' and 'Signal' operations are used to implement which synchronization tool?", o: ["A) Mutex", "B) Semaphores", "C) Monitors", "D) Critical Section"], "a": 1 },
  { "q": "Which mapping technique in Cache Memory allows a block of main memory to be placed anywhere in the cache?", o: ["A) Direct Mapping", "B) Set-Associative Mapping", "C) Fully Associative Mapping", "D) Block Mapping"], "a": 2 },
  { "q": "What is the result of 'X ⊕ X' (X XOR X) in Digital Logic?", o: ["A) 1", "B) X", "C) X'", "D) 0"], "a": 3 },
  { "q": "Which traversal is used to evaluate a Prefix expression using a stack?", o: ["A) Left to Right", "B) Right to Left", "C) Random", "D) Top to Bottom"], "a": 1 },
        
   
  { "q": "Which of the following is a method to prevent deadlock by violating the 'Hold and Wait' condition?", o: ["A) Resource Preemption", "B) Request all resources at start", "C) Circular Ordering", "D) Process Termination"], "a": 1 },
  { "q": "In a B+ Tree, where are the actual data pointers (or records) stored?", o: ["A) Root Node only", "B) Internal Nodes only", "C) Leaf Nodes only", "D) All Nodes"], "a": 2 },
  { "q": "What is the excess bias used in IEEE 754 Single Precision floating-point representation?", o: ["A) 127", "B) 128", "C) 1023", "D) 64"], "a": 0 },
  { "q": "Which graph algorithm uses a 'Greedy' approach to find the shortest path from a single source?", o: ["A) Bellman-Ford", "B) Floyd-Warshall", "C) Dijkstra's Algorithm", "D) Kruskal's Algorithm"], "a": 2 },
  { "q": "What is the range of a signed 8-bit integer using 2's complement representation?", o: ["A) -128 to 127", "B) -127 to 128", "C) 0 to 255", "D) -256 to 255"], "a": 0 },
  { "q": "In an Operating System, 'Dirty Bit' is used to indicate which of the following?", o: ["A) Page is corrupted", "B) Page has been modified", "C) Page is empty", "D) Page is being read"], "a": 1 },
  { "q": "Which data structure is primarily used for implementing a LIFO (Last-In-First-Out) mechanism?", o: ["A) Queue", "B) Linked List", ",C) Stack", "D) Binary Tree"], "a": 2 },
  { "q": "A 4-bit synchronous counter uses how many flip-flops?", o: ["A) 2", "B) 4", "C) 8", "D) 16"], "a": 1 },
  { "q": "Which CPU scheduling algorithm is non-preemptive by nature?", o: ["A) Round Robin", "B) SRTF", "C) FCFS", "D) Priority Scheduling (Preemptive)"], "a": 2 },
  { "q": "What is the worst-case time complexity of searching in a Hash Table if all elements hash to the same slot?", o: ["A) O(1)", "B) O(log n)", "C) O(n)", "D) O(n log n)"], "a": 2 }
          
        ] },
       
       
        "Set 3": { pass: "8901", msg: motives[2], questions: [
  
  { "q": "In a paged memory management, if the page size is 4KB, how many bits are required for the 'Offset'?", o: ["A) 10", "B) 12", "C) 14", "D) 16"], "a": 1 },
  { "q": "Which data structure is required to check if an expression has balanced parentheses?", o: ["A) Queue", "B) Stack", "C) Tree", "D) Array"], "a": 1 },
  { "q": "How many 4x1 Multiplexers are needed to implement a 16x1 Multiplexer?", o: ["A) 4", "B) 5", "C) 3", "D) 8"], "a": 1 },
  { "q": "What is the result of an 'In-order' traversal of a Binary Search Tree (BST)?", o: ["A) Random order", "B) Decreasing order", "C) Increasing order", "D) Level order"], "a": 2 },
  { "q": "Which of the following is a solution to the 'External Fragmentation' problem?", o: ["A) Paging", "B) Segmentation", "C) Compaction", "D) Both A and C"], "a": 3 },
  { "q": "In an AVL tree, what is the maximum permissible 'Balance Factor' for any node?", o: ["A) 0", "B) 1", "C) 2", "D) -2"], "a": 1 },
  { "q": "Which logic gate outputs 1 only when all its inputs are 0?", o: ["A) NAND", "B) NOR", "C) AND", "D) OR"], "a": 1 },
  { "q": "The time complexity of 'Quick Sort' in its worst-case scenario is:", o: ["A) O(n log n)", "B) O(n^2)", "C) O(n)", "D) O(log n)"], "a": 1 },
  { "q": "A 'Race Condition' occurs in which of the following scenarios?", o: ["A) Deadlock", "B) Critical Section access", "C) Spooling", "D) Throughput increase"], "a": 1 },
  { "q": "What is the minimum number of colors required to color a 'Cycle Graph' with 5 vertices (C5)?", o: ["A) 2", "B) 3", "C) 4", "D) 5"], "a": 1 },
  
  { "q": "In 8085 Microprocessor, which interrupt has the highest priority?", o: ["A) INTR", "B) TRAP", "C) RST 7.5", "D) RST 6.5"], "a": 1 },
  { "q": "Which collision resolution technique in Hashing is known as 'Closed Hashing'?", o: ["A) Chaining", "B) Linear Probing", "C) Double Hashing", "D) Both B and C"], "a": 3 },
  { "q": "A system has 3 processes and each needs 2 resources. What is the minimum number of resources to ensure no deadlock?", o: ["A) 3", "B) 4", "C) 5", "D) 6"], "a": 1 },
  { "q": "What is the post-order traversal of a binary tree if the pre-order is ABC and in-order is BAC?", o: ["A) BCA", "B) ACB", "C) CBA", "D) CAB"], "a": 0 },
  { "q": "Which flip-flop is used to eliminate the 'Race Around Condition'?", o: ["A) SR Flip-Flop", "B) JK Flip-Flop", "C) Master-Slave JK", "D) D Flip-Flop"], "a": 2 },
  { "q": "The time complexity of building a heap of 'n' elements is:", o: ["A) O(n log n)", "B) O(n)", "C) O(log n)", "D) O(n^2)"], "a": 1 },
  { "q": "Which memory is non-volatile and can be erased by exposing it to UV light?", o: ["A) ROM", "B) PROM", "C) EPROM", "D) EEPROM"], "a": 2 },
  { "q": "In an OS, which component is responsible for loading the kernel into memory after a system reset?", "o": ["A) Compiler", "B) Bootstrap Loader", "C) Linker", "D) Shell"], "a": 1 },
  { "q": "What is the maximum number of edges in a simple bipartite graph with 'n' vertices?", o: ["A) n^2/4", "B) n(n-1)/2", "C) n-1", "D) n log n"], "a": 0 },
  { "q": "Which logic circuit is used to perform the addition of three 1-bit binary numbers?", o: ["A) Half Adder", "B) Full Adder", "C) Decoder", "D) Multiplexer"], "a": 1 }

] },
        "Set 4": { pass: "1234", msg: motives[3], questions: [

   
  { "q": "In a 2-way Set Associative Cache, if the total number of blocks is 64, how many 'Sets' are there?", o: ["A) 64", "B) 32", "C) 16", "D) 128"], "a": 1 },
  { "q": "Which data structure is used by the OS to keep track of all free memory blocks?", o: ["A) Stack", "B) Hash Table", "C) Linked List", "D) Queue"], "a": 2 },
  { "q": "What is the maximum number of edges in a directed graph with 'n' vertices and no self-loops?", o: ["A) n(n-1)/2", "B) n(n-1)", "C) n^2", "D) 2n"], "a": 1 },
  { "q": "Which of the following is a 'Universal Gate' along with NAND?", o: ["A) XOR", "B) NOR", "C) AND", "D) NOT"], "a": 1 },
  { "q": "The time complexity to find an element in a Balanced Binary Search Tree (BST) is:", o: ["A) O(n)", "B) O(log n)", "C) O(1)", "D) O(n log n)"], "a": 1 },
  { "q": "Which register in 8085 is not accessible to the programmer?", o: ["A) Accumulator", "B) Instruction Register", "C) Program Counter", "D) Stack Pointer"], "a": 1 },
  { "q": "What is the 'Best Fit' memory allocation strategy?", o: ["A) Allocates first hole", "B) Allocates smallest sufficient hole", "C) Allocates largest hole", "D) Allocates last hole"], "a": 1 },
  { "q": "How many states are required to represent a Mod-10 counter?", "o": ["A) 4", "B) 8", "C) 10", "D) 16"], "a": 2 },
  { "q": "In Hashing, what is 'Primary Clustering' associated with?", o: ["A) Linear Probing", "B) Quadratic Probing", "C) Double Hashing", "D) Chaining"], "a": 0 },
  { "q": "A tree with 'n' vertices always has exactly how many edges?", o: ["A) n", "B) n+1", "C) n-1", "D) 2n"], "a": 2 },
  // ... Paste 18 more similar logic questions for Set 4 ...
  
  { "q": "Which I/O technique allows a device to transfer data directly to/from memory without involving the CPU?", o: ["A) Programmed I/O", "B) Interrupt-driven I/O", "C) DMA (Direct Memory Access)", "D) Polling"], "a": 2 },
  { "q": "In a B-Tree of order 4, what is the maximum number of keys a node can contain?", o: ["A) 4", "B) 3", "C) 2", "D) 5"], "a": 1 },
  { "q": "Which gate is used to implement the 'Parity Generator' circuit?", o: ["A) NAND", "B) XOR", "C) OR", "D) AND"], "a": 1 },
  { "q": "What is the size of the physical address space if the system uses 32-bit addresses?", o: ["A) 2 GB", "B) 4 GB", "C) 8 GB", "D) 16 GB"], "a": 1 },
  { "q": "Which data structure is most suitable for implementing a 'Priority Queue' efficiently?", o: ["A) Linked List", "B) Stack", "C) Heap", "D) Array"], "a": 2 },
  { "q": "In an 8085 microprocessor, which flag is affected when the result of an operation is zero?", o: ["A) Carry Flag", "B) Sign Flag", "C) Zero Flag", "D) Parity Flag"], "a": 2 },
  { "q": "What is the time complexity of deleting a node from a Doubly Linked List, given the pointer to that node?", o: ["A) O(n)", "B) O(log n)", "C) O(1)", "D) O(n^2)"], "a": 2 },
  { "q": "Which of the following is a 'Self-Complementing' code?", o: ["A) 8421 Code", "B) Excess-3 Code", "C) Gray Code", "D) Binary Code"], "a": 1 },
  { "q": "The 'LRU' (Least Recently Used) page replacement policy is based on which principle?", o: ["A) Principle of Locality", "B) Belady's Anomaly", "C) First-In-First-Out", "D) Random Selection"], "a": 0 },
  { "q": "How many 1-to-2 Decoders are needed to build a 3-to-8 Decoder?", o: ["A) 4", "B) 6", "C) 7", "D) 8"], "a": 2 }


        ] },
        "Set 5": { pass: "1234", msg: motives[4], questions: [
            // quizData["Set 5"].questions
           
    // --- DSA ---
   
  { "q": "Which memory management technique divides the program into logical units like functions and objects?", o: ["A) Paging", "B) Segmentation", "C) Swapping", "D) Contiguous Allocation"], "a": 1 },
  { "q": "What is the minimum number of stacks required to implement a Queue?", o: ["A) 1", "B) 2", "C) 3", "D) 4"], "a": 1 },
  { "q": "In a 4-variable K-Map, what does a 'Don't Care' condition (X) represent?", o: ["A) Always 0", "B) Always 1", "C) Can be 0 or 1", "D) Invalid Input"], "a": 2 },
  { "q": "Which algorithm is used to find the 'Shortest Path' in a weighted graph with negative edge weights (but no negative cycles)?", "o": ["A) Dijkstra's", "B) Bellman-Ford", "C) Prim's", "D) Kruskal's"], "a": 1 },
  { "q": "The 'Bus' used to identify a specific memory location or I/O port is called?", o: ["A) Data Bus", "B) Control Bus", "C) Address Bus", "D) System Bus"], "a": 2 },
  { "q": "What is the time complexity of the 'Kruskal's Algorithm' using a Disjoint Set Union (DSU)?", o: ["A) O(V^2)", "B) O(E log E)", "C) O(E + V)", "D) O(V log V)"], "a": 1 },
  { "q": "Which register is typically used to store the results of arithmetic and logical operations in a CPU?", o: ["A) Program Counter", "B) Instruction Register", "C) Accumulator", "D) Flag Register"], "a": 2 },
  { "q": "In an OS, 'Belady’s Anomaly' occurs when increasing page frames leads to more page faults. This happens in:", o: ["A) LRU", "B) FIFO", "C) Optimal", "D) Stack-based algorithms"], "a": 1 },
  { "q": "A full-adder can be implemented using how many half-adders and OR gates?", o: ["A) 2 Half-Adders, 1 OR gate", "B) 1 Half-Adder, 2 OR gates", "C) 2 Half-Adders, 2 OR gates", "D) 3 Half-Adders, 0 OR gates"], "a": 0 },
  { "q": "Which data structure is best for implementing a 'Undo' feature in a text editor?", o: ["A) Queue", "B) Linked List", "C) Stack", "D) Tree"], "a": 2 },

    // --- Digital Logic ---
     
  { "q": "Which synchronization mechanism is a hardware-based solution to the Critical Section problem?", o: ["A) Semaphores", "B) Test-and-Set Instruction", "C) Monitors", "D) Peterson's Solution"], "a": 1 },
  { "q": "In a Hash Table, what is the 'Load Factor' defined as?", o: ["A) Number of slots / Number of elements", "B) Number of elements / Number of slots", "C) Number of collisions / Number of elements", "D) Max elements * Number of slots"], "a": 1 },
  { "q": "Which shift register allows data to be entered bit-by-bit and retrieved bit-by-bit?", o: ["A) PIPO", "B) PISO", "C) SISO", "D) SIPO"], "a": 2 },
  { "q": "A Binary Tree is 'Threaded' to make which traversal faster and without recursion?", o: ["A) Pre-order", "B) Post-order", "C) In-order", "D) Level-order"], "a": 2 },
  { "q": "What is the time complexity of 'Heapify' operation for a single node?", o: ["A) O(1)", "B) O(n)", "C) O(log n)", "D) O(n log n)"], "a": 2 },
  { "q": "The 'Dirty Bit' in a Page Table entry is primarily used for which purpose?", o: ["A) Page protection", "B) Reducing write-backs to disk", "C) Speeding up address translation", "D) Identifying free frames"], "a": 1 },
  { "q": "Which logic family is known for the lowest power consumption?", o: ["A) TTL", "B) ECL", "C) CMOS", "D) RTL"], "a": 2 },
  { "q": "In a Directed Acyclic Graph (DAG), the 'Topological Sort' is possible only if there are no:", o: ["A) Source nodes", "B) Sink nodes", "C) Cycles", "D) Isolated vertices"], "a": 2 },
  { "q": "Which CPU register stores the address of the data currently being accessed?", o: ["A) Program Counter", "B) Memory Address Register", "3) Accumulator", "4) Stack Pointer"], "a": 1 },
  { "q": "What is the degree of a leaf node in any tree structure?", o: ["A) 0", "B) 1", "C) 2", "D) Depends on the tree type"], "a": 0 }

        ] },

        
        "Set 6": { pass: "1234", msg: motives[5], questions: [
                  // quizData["Set 6"].questions
                
    // --- OS (Operating Systems) ---
    
  { "q": "Which process state transition is valid only in a Preemptive Scheduling system?", o: ["A) Running to Waiting", "B) Running to Ready", "C) Waiting to Ready", "D) Ready to Running"], "a": 1 },
  { "q": "What is the maximum height of a Red-Black Tree with 'n' nodes?", o: ["A) log(n)", "B) 2 log(n+1)", "C) n-1", "D) sqrt(n)"], "a": 1 },
  { "q": "In a 16-bit address bus, what is the total number of unique memory locations that can be addressed?", o: ["A) 16,000", "B) 32,768", "C) 65,536", "D) 1,048,576"], "a": 2 },
  { "q": "Which data structure is used to convert an Infix expression to a Postfix expression?", o: ["A) Queue", "B) Stack", "C) Linked List", "D) Binary Tree"], "a": 1 },
  { "q": "A 'Race Around Condition' occurs in a JK Flip-Flop when:", o: ["A) J=0, K=0", "B) J=1, K=0", "C) J=0, K=1", "D) J=1, K=1 and Enable=1"], "a": 3 },
  { "q": "What is the time complexity of the 'Breadth-First Search (BFS)' algorithm using an Adjacency List?", o: ["A) O(V^2)", "B) O(V+E)", "C) O(E log V)", "D) O(V)"], "a": 1 },
  { "q": "The 'Wait-for Graph' is used in an Operating System for which of the following?", o: ["A) Deadlock Avoidance", "B) Deadlock Detection", "C) CPU Scheduling", "D) Memory Management"], "a": 1 },
  { "q": "In a Min-Heap, the element at the root is always:", o: ["A) The Largest", "B) The Smallest", "C) Zero", "D) Random"], "a": 1 },
  { "q": "How many select lines are needed for a 1-to-8 Demultiplexer?", o: ["A) 2", "B) 3", "C) 4", "D) 8"], "a": 1 },
  { "q": "Which sorting algorithm works by repeatedly picking the smallest element and swapping it into its correct position?", o: ["A) Bubble Sort", "B) Insertion Sort", "C) Selection Sort", "D) Quick Sort"], "a": 2 },


    // --- DSA (Data Structures & Algorithms) ---
   
  { "q": "In which state of the instruction cycle is the operand address calculated?", o: ["A) Fetch", "B) Decode", "C) Execute", "D) Indirect"], "a": 1 },
  { "q": "What is the time complexity to find the 'Diameter' of a Binary Tree efficiently?", o: ["A) O(n^2)", "B) O(n)", "C) O(log n)", "D) O(1)"], "a": 1 },
  { "q": "A 'JK Flip-Flop' can be converted into a 'T Flip-Flop' by doing which of the following?", o: ["A) Connecting J to K", "B) Connecting J and K together", "C) Setting J=0, K=1", "D) Setting J=1, K=1"], "a": 1 },
  { "q": "Which disk scheduling algorithm is also known as the 'Elevator Algorithm'?", o: ["A) FCFS", "B) SSTF", "C) SCAN", "D) C-SCAN"], "a": 2 },
  { "q": "In Hashing, if two different keys produce the same hash value, it is called a:", o: ["A) Clustering", "B) Overflow", "C) Collision", "D) Probing"], "a": 2 },
  { "q": "Which register holds the current instruction while it is being decoded and executed?", o: ["A) PC", "B) IR", "C) MAR", "D) MDR"], "a": 1 },
  { "q": "Which of the following is an example of a 'Greedy' algorithm?", o: ["A) 0/1 Knapsack", "B) Huffman Coding", "C) Matrix Chain Multiplication", "D) Floyd-Warshall"], "a": 1 },
  { "q": "The number of flip-flops required for a Decade Counter is:", o: ["A) 3", "B) 4", "C) 10", "D) 2"], "a": 1 },
  { "q": "What is the primary advantage of using a 'B+ Tree' over a 'B-Tree' for database indexing?", o: ["A) Faster search", "B) Sequential access of data", "C) Smaller tree height", "D) Less memory"], "a": 1 },
  { "q": "Which policy is used by the OS to handle the 'Critical Section' problem for multiple processes?", o: ["A) Aging", "B) Mutual Exclusion", "C) Spooling", "D) Compaction"], "a": 1 }


        ] },

        "Set 7": { pass: "1234", msg: motives[0], questions: [
            // quizData["Set 7"].questions
            //cs QUESTION
    // --- ADVANCED OS (Kernel & Concurrency) ---
   
  { "q": "In a paged system, if the Page Table is stored in main memory, how many memory accesses are required to fetch one data word?", o: ["A) 1", "B) 2", "C) 3", "D) 4"], "a": 1 },
  { "q": "What is the maximum number of edges in a simple graph with 'n' vertices that is NOT connected?", o: ["A) n-1", "B) (n-1)(n-2)/2", "C) n(n-1)/2", "D) n-2"], "a": 1 },
  { "q": "Which interrupt in 8085 is edge-triggered as well as level-triggered?", o: ["A) TRAP", "B) RST 7.5", "C) RST 6.5", "D) RST 5.5"], "a": 0 },
  { "q": "A queue is implemented using an array. If 'front' is 4 and 'rear' is 2 in a circular queue of size 5, how many elements are there?", "o": ["A) 2", "B) 3", "C) 4", "D) 5"], "a": 1 },
  { "q": "Which logic gate is used to compare two binary bits and outputs 1 if they are different?", o: ["A) AND", "B) OR", "C) XOR", "D) XNOR"], "a": 2 },
  { "q": "In COA, which instruction format is used in 'Stack-based Architecture'?", o: ["A) Zero-address", "B) One-address", "C) Two-address", "D) Three-address"], "a": 0 },
  { "q": "What is the time complexity to find the 'Middle Element' of a Singly Linked List in one pass?", o: ["A) O(n^2)", "B) O(n)", "C) O(log n)", "D) O(1)"], "a": 1 },
  { "q": "Which memory replacement policy is based on the 'Temporal Locality' of reference?", o: ["A) FIFO", "B) LRU", "C) LIFO", "D) Optimal"], "a": 1 },
  { "q": "The number of distinct Binary Search Trees (BST) that can be formed with 3 distinct keys is:", o: ["A) 3", "0) 4", "C) 5", "D) 6"], "a": 2 },
  { "q": "Which device is used to convert Parallel data into Serial data?", o: ["A) Decoder", "B) Multiplexer", "C) Demultiplexer", "D) Encoder"], "a": 1 },

    // --- ADVANCED DSA (Complexities & Trees) ---

  { "q": "In a 4-way Set Associative mapping, a main memory block can be placed in how many possible cache locations?", o: ["A) 1", "B) 2", "C) 4", "D) Any location"], "a": 2 },
  { "q": "Which of the following is NOT a stable sorting algorithm?", o: ["A) Bubble Sort", "B) Insertion Sort", "C) Quick Sort", "D) Merge Sort"], "a": 2 },
  { "q": "The 'Priority Inversion' problem in Operating Systems can be solved using which protocol?", o: ["A) Banker's Protocol", "B) Priority Inheritance Protocol", "C) Two-Phase Locking", "D) Aging"], "a": 1 },
  { "q": "How many states are in a 3-bit Ripple Counter?", o: ["A) 3", "B) 6", "C) 8", "D) 16"], "a": 2 },
  { "q": "What is the time complexity of Dijkstra's algorithm using an Adjacency Matrix?", o: ["A) O(E log V)", "B) O(V^2)", "C) O(V + E)", "D) O(V^3)"], "a": 1 },
  { "q": "Which CPU register is used to point to the top of the stack memory?", o: ["A) Program Counter", "B) Accumulator", "C) Stack Pointer", "D) Data Register"], "a": 2 },
  { "q": "What is the maximum number of nodes at level 'L' of a binary tree (root is at level 0)?", o: ["A) 2^L", "B) 2^(L+1)", "C) 2^L - 1", "D) L^2"], "a": 0 },
  { "q": "A Latch is a ______-triggered circuit, while a Flip-Flop is a ______-triggered circuit.", o: ["A) Edge, Level", "B) Level, Edge", "C) Level, Level", "D) Edge, Edge"], "a": 1 },
  { "q": "Which data structure is used to implement a 'Recursion Tree' during function calls?", o: ["A) Queue", "B) Stack", "C) Heap", "D) Hash Table"], "a": 1 },
  { "q": "Which memory type is used as 'Main Memory' in most modern computers?", o: ["A) SRAM", "B) DRAM", "C) ROM", "D) Magnetic Disk"], "a": 1 }

    // --- ADVANCED DIGITAL LOGIC & ARCHITECTURE ---


    // --- CS CONCEPTS (DBMS, Networks, Logic) ---
    
        ] },
        "Set 8": { pass: "1234", msg: motives[1], questions: [
            // quizData["Set 8"].questions
            //cs QUESTION
    // --- OPERATING SYSTEMS (CPU, Memory, Deadlocks) ---
    
  { "q": "Which cache write policy updates both the cache and the main memory simultaneously?", o: ["A) Write-back", "B) Write-through", "C) Write-around", "D) No-write"], "a": 1 },
  { "q": "If the In-order traversal of a tree is D B E A F C and Pre-order is A B D E C F, what is the Post-order?", o: ["A) D E B F C A", "B) D E B F A C", "C) D B E F C A", "D) A B C D E F"], "a": 0 },
  { "q": "Which interrupt is used for 'Input/Output' data transfer between the CPU and peripherals?", o: ["A) Maskable", "B) Non-maskable", "C) Vector", "D) Software"], "a": 0 },
  { "q": "What is the time complexity to find the 'Transpose' of an N x N matrix?", o: ["A) O(1)", "B) O(N)", "C) O(N^2)", "D) O(log N)"], "a": 2 },
  { "q": "In a Full-Adder, the 'Carry' output is equivalent to which Boolean expression?", o: ["A) AB + BC + AC", "B) A + B + C", "C) A ⊕ B ⊕ C", "D) (A+B)C"], "a": 0 },
  { "q": "Which scheduling algorithm is specifically designed for 'Time-Sharing' systems?", o: ["A) FCFS", "B) Round Robin", "C) SJF", "D) Multilevel Queue"], "a": 1 },
  { "q": "A 'B-Tree' of order 5 can have a maximum of how many children per node?", o: ["A) 4", "B) 5", "C) 6", "D) 10"], "a": 1 },
  { "q": "Which flip-flop is ideal for storing a single bit of data without any toggle issues?", o: ["A) T Flip-Flop", "B) D Flip-Flop", "C) JK Flip-Flop", "D) SR Latch"], "a": 1 },
  { "q": "The 'Wait' operation on a semaphore decrements its value. If the value becomes negative, the process is?", o: ["A) Terminated", "B) Blocked", "C) Running", "D) Ready"], "a": 1 },
  { "q": "How many gates are required to implement a 'Half-Adder' (using only XOR and AND)?", o: ["A) 1 XOR, 1 AND", "B) 2 XOR, 1 AND", "C) 1 XOR, 2 AND", "D) 2 XOR, 2 AND"], "a": 0 },
  
  { "q": "In which addressing mode is the operand's address found in a CPU register?", o: ["A) Immediate", "B) Direct", "C) Register Indirect", "D) Relative"], "a": 2 },
  { "q": "What is the maximum number of comparisons needed in a Binary Search for an array of size 1024?", o: ["A) 10", "B) 11", "C) 512", "D) 1024"], "a": 1 },
  { "q": "Which data structure is most efficient to find the shortest path in an unweighted graph?", o: ["A) DFS (Stack)", "B) BFS (Queue)", "C) Binary Tree", "D) Min-Heap"], "a": 1 },
  { "q": "A system has 4 page frames. The page reference string is 1, 2, 3, 4, 5. Using FIFO, how many page faults occur?", o: ["A) 4", "B) 5", "C) 1", "D) 0"], "a": 1 },
  { "q": "Which of the following is used to implement a 'Priority Queue' where both insertion and deletion are O(log n)?", o: ["A) Unsorted Array", "B) Sorted Linked List", "C) Binary Heap", "D) Hash Table"], "a": 2 },
  { "q": "How many outputs are there in a standard n-to-2^n Decoder?", o: ["A) n", "B) 2n", "C) 2^n", "D) n^2"], "a": 2 },
  { "q": "In an OS, 'Context Switching' is the responsibility of which component?", "o": ["A) Long-term Scheduler", "B) Dispatcher", "C) Compiler", "D) Assembler"], "a": 1 },
  { "q": "Which property of a 'B+ Tree' makes it suitable for range queries in Databases?", o: ["A) Internal nodes store data", "B) Leaf nodes are linked", "C) All nodes are roots", "D) It is a binary tree"], "a": 1 },
  { "q": "The 'Race Around Condition' occurs when the propagation delay of a flip-flop is _____ the pulse width of the clock.", o: ["A) Greater than", "B) Smaller than", "C) Equal to", "D) Not related to"], "a": 1 },
  { "q": "What is the result of 'A + AB' in Boolean Algebra?", o: ["A) B", "B) AB", "C) A", "D) A+B"], "a": 2 }

        ] },


        "Set 9": { pass: "1234", msg: motives[2], questions: [
            // quizData["Set 9"].questions
    // --- ADVANCED OPERATING SYSTEMS (Concurrency, Paging, Scheduling) ---
    { q: "Which of the following conditions is sufficient to prevent deadlock in a system with one instance of each resource type?", o: ["Mutual Exclusion", "Hold and Wait", "No Preemption", "Circular Wait"], a: 3 },
    { q: "What is the primary objective of a Long-Term Scheduler?", o: ["Manage I/O queues", "Select which processes are brought into the ready queue", "Manage swapping", "Allocate CPU to a process"], a: 1 },
    { q: "The time required for the CPU to stop the current process, save its state, and load the new process state is known as?", o: ["Latency", "Throughput", "Context Switch Time", "Burst Time"], a: 2 },
    { q: "In a 'Microkernel' OS design, which component typically resides in user space?", o: ["CPU Scheduler", "Hardware Abstraction Layer", "Device Drivers", "Interrupt Handler"], a: 2 },
    { q: "Which page replacement algorithm can be practically implemented and closely approximates Optimal PR?", o: ["FIFO", "LRU", "MRU", "LIFO"], a: 1 },
    { q: "A system is in an 'unsafe state'. What does this imply?", o: ["Deadlock is imminent", "System is deadlocked", "Deadlock is possible but not guaranteed", "System is safe"], a: 2 },
    { q: "The 'TestAndSet' instruction is a hardware solution used to solve which problem?", o: ["Deadlock prevention", "Critical Section Problem", "Starvation", "Aging"], a: 1 },
    { q: "Which scheduling algorithm is associated with the 'Convoy Effect'?", o: ["SJF", "Round Robin", "Priority", "FCFS"], a: 3 },
    { q: "In Paging, the logical address space size depends on?", o: ["RAM size", "Hard disk size", "Address bus size", "User choice"], a: 2 },
    { q: "Which of these is used for inter-process communication (IPC) via message passing in Unix?", o: ["Semaphore", "Shared Memory", "Pipe", "Monitor"], a: 2 },

    // --- ADVANCED DATA STRUCTURES & ALGORITHMS (Complexity, Trees, Graphs) ---
    { q: "What is the worst-case time complexity of inserting a key into a Binary Search Tree?", o: ["O(log n)", "O(n log n)", "O(n)", "O(1)"], a: 2 },
    { q: "The time complexity of the Floyd-Warshall algorithm for all-pairs shortest paths in a graph with V vertices is?", o: ["O(V^2)", "O(E log V)", "O(V + E)", "O(V^3)"], a: 3 },
    { q: "Which sorting algorithm's best-case time complexity is O(n log n) but can degrade to O(n^2)?", o: ["Merge Sort", "Insertion Sort", "Quick Sort", "Bubble Sort"], a: 2 },
    { q: "Which data structure is typically used for implementing Dijkstra's shortest path algorithm efficiently?", o: ["Stack", "Queue", "Min-Heap (Priority Queue)", "Array"], a: 2 },
    { q: "The balance factor of an AVL tree node can be?", o: ["-1, 0, or 1", "-2, -1, 0, 1, or 2", "Any integer", "0 only"], a: 0 },
    { q: "Which algorithm finds the Minimum Spanning Tree using a greedy approach based on edges?", o: ["Prim's", "Dijkstra's", "Kruskal's", "BFS"], a: 2 },
    { q: "In a max-heap implemented as an array, where can the smallest element be found?", o: ["Always the last element", "Always a leaf node", "At the root", "Anywhere in the lower half"], a: 3 },
    { q: "What is the recurrence relation for the Tower of Hanoi problem?", o: ["T(n) = T(n-1) + 1", "T(n) = 2T(n-1) + 1", "T(n) = 2T(n/2) + n", "T(n) = T(n-1) + n"], a: 1 },
    { q: "Which of the following is an application of the Queue data structure?", o: ["Function call management", "Infix to Postfix conversion", "Level order traversal of a tree", "Undo operation in editor"], a: 2 },
    { q: "The expected average time complexity for searching in a well-implemented Hash Table with chaining is?", o: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], a: 3 },

        ] },
        "Set 10": { pass: "1234", msg: motives[3], questions: [
            // quizData["Set 10"].questions
    // --- Set 10: Operating Systems (Advanced/Mixed) ---
    { q: "In the Paging model, 'Internal Fragmentation' is calculated as the total unused space in the last frame of every process's address space.", o: ["True", "False"], a: 0 },
    { q: "Which component of the OS keeps track of who is using which part of the memory, disk space, and all files/directories?", o: ["Process Manager", "CPU Scheduler", "Resource Manager / File Manager", "Networking Manager"], a: 2 },
    { q: "What is a 'Spinlock'?", o: ["A type of physical lock on hard disk", "A lock that involves busy waiting (looping)", "A lock that forces immediate context switch", "A memory access protection mechanism"], a: 1 },
    { q: "If a system has 5 processes and 3 tape drives (maximum need per process is 3, current allocation is 1 each), can a deadlock occur?", o: ["Yes", "No", "Maybe, depends on scheduler", "Only in FCFS"], a: 1 },
    { q: "Which scheduling objective aims to maximize CPU usage over a period of time?", o: ["Response Time", "Throughput", "Latency", "Turnaround Time"], a: 1 },
    { q: "What is the primary role of the 'System Call Interface'?", o: ["Interface for user programs to request kernel services", "Interface between hardware and kernel", "Interface between kernel and memory", "Interface for networking protocols"], a: 0 },
    { q: "Which RAID level uses disk striping with parity information distributed across all drives?", o: ["RAID 0", "RAID 1", "RAID 5", "RAID 10"], a: 2 },
    { q: "What is the main reason for using a 'Microkernel' architecture?", o: ["Faster execution speed", "Increased reliability and security", "Simpler device driver coding", "Lower memory consumption"], a: 1 },
    { q: "Which type of fragmentation cannot be solved by defragmentation tools?", o: ["External Fragmentation", "Internal Fragmentation"], a: 1 },
    { q: "Which mechanism ensures that if any process holds one resource, it cannot request another resource simultaneously?", o: ["Mutual Exclusion", "No Preemption", "Hold and Wait (Denial of)", "Circular Wait (Denial of)"], a: 2 },

    // --- Set 10: DSA (Advanced/Mixed) ---
    { q: "What is the time complexity of Dijkstra's algorithm if implemented using an array (not a heap)?", o: ["O(E log V)", "O(V^3)", "O(V+E)", "O(V^2)"], a: 3 },
    { q: "Which traversal technique of a binary tree visits the right child, then the root, then the left child?", o: ["Pre-order", "In-order", "Post-order", "Reverse In-order"], a: 3 },
    { q: "The worst-case scenario for Quick Sort occurs when the pivot is always chosen as?", o: ["The middle element", "A random element", "The smallest/largest element", "The median element"], a: 2 },
    { q: "Which sorting algorithm performs best on nearly sorted data, with O(n) in the best case?", o: ["Merge Sort", "Quick Sort", "Insertion Sort", "Selection Sort"], a: 2 },
    { q: "A 'Trie' data structure is primarily used for efficient?", o: ["Sorting numbers", "Searching strings by prefix", "Graph traversal", "Implementing hash functions"], a: 1 },
    { q: "What is the amortized time complexity of deleting an element from a dynamically allocated hash map using chaining?", o: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], a: 2 },
    { q: "In a Red-Black tree, which color is used to maintain balance and ensure no long paths exist?", o: ["Blue", "Green", "Red/Black", "White"], a: 2 },
    { q: "What is the minimum number of nodes in an AVL tree of height 3?", o: ["7", "14", "4", "2"], a: 2 },
    { q: "The number of edges in a directed acyclic graph (DAG) with N vertices must be less than or equal to?", o: ["N^2", "N!", "N * (N-1) / 2", "V^2"], a: 3 },
    { q: "What problem does the 'Union-Find' data structure solve efficiently?", o: ["Shortest path finding", "Sorting a list", "Checking graph connectivity/cycles", "String searching"], a: 2 },

        ] }
    };

    let activeSet = null, curr = 0, userAns = [], qStatus = [], timeLeft = 1200;

    function initHome() {
        const grid = document.getElementById("test-grid");
        document.getElementById("home-quote").innerText = `"${motives[Math.floor(Math.random() * motives.length)]}"`;
        Object.keys(quizData).forEach(name => {
            grid.innerHTML += `<div class="p-card"><h3>${name}</h3><p class="desc">MCA Mock Test Series.</p><button class="action-btn" onclick="openGate('${name}')">Start Test</button></div>`;
        });
    }

    function openGate(name) { activeSet = name; document.getElementById("home-screen").style.display = "none"; document.getElementById("lock-screen").style.display = "block"; }
    function checkAccess() {
        if(document.getElementById("pass-code").value === quizData[activeSet].pass) {
            document.getElementById("lock-screen").style.display = "none"; document.getElementById("exam-screen").style.display = "flex";
            const qCount = quizData[activeSet].questions.length || 75;
            userAns = new Array(qCount).fill(null); qStatus = new Array(qCount).fill('not-visited');
            loadStep(0); setInterval(runClock, 1000);
        } else { alert("Access Denied!"); }
    }

    function loadStep(i) {
        curr = i; const data = quizData[activeSet].questions[i] || { q: "Questions loading in Step 7...", o: ["A","B","C","D"], a: 0 };
        document.getElementById("q-label").innerText = `Question ${i+1}`; 
        document.getElementById("q-text").innerHTML = data.q;
        const opts = document.getElementById("opt-container"); opts.innerHTML = "";
        data.o.forEach((txt, idx) => { const cls = (userAns[curr] === idx) ? 'selected' : ''; opts.innerHTML += `<button class="opt-btn ${cls}" onclick="pick(${idx})">${txt}</button>`; });
        renderMathInElement(document.body, { delimiters: [{left: "$", right: "$", display: false}] });
        refreshPalette();
    }

    function refreshPalette() {
        const grid = document.getElementById("palette-grid"), count = quizData[activeSet].questions.length || 75; grid.innerHTML = "";
        for(let i=0; i<count; i++) grid.innerHTML += `<div class="q-box ${qStatus[i]} ${i===curr?'active':''}" onclick="loadStep(${i})">${i+1}</div>`;
    }

    function pick(idx) { userAns[curr] = idx; loadStep(curr); }
    function clearStep() { userAns[curr] = null; qStatus[curr] = 'not-visited'; loadStep(curr); }
    function prevStep() { if(curr > 0) loadStep(curr-1); }
    function nextStep() { if(curr < userAns.length-1) loadStep(curr+1); }
    function markStep() { qStatus[curr] = 'review'; autoMove(); }
    function saveStep() { qStatus[curr] = (userAns[curr] !== null) ? 'answered' : 'not-visited'; autoMove(); }
    function autoMove() { if(curr < userAns.length-1) loadStep(curr+1); else refreshPalette(); }
    function runClock() { timeLeft--; let m = Math.floor(timeLeft/60), s = timeLeft%60; document.getElementById("cbt-timer").innerText = `TIME: ${m}:${s<10?'0'+s:s}`; if(timeLeft <= 0) finalize(); }
    function confirmSubmit() { if(confirm("Submit?")) finalize(); }

    function finalize() {
        document.getElementById("exam-screen").style.display = "none"; document.getElementById("result-screen").style.display = "flex";
        let total = 0, correct = 0, wrong = 0, skipped = 0, cs = 0, math = 0, reason = 0;
        userAns.forEach((ans, i) => {
            const actual = quizData[activeSet].questions[i]?.a;
            if(ans === null) skipped++;
            else if(ans === actual) { correct++; total += 4; if(i<40) cs+=4; else if(i<63) math+=4; else reason+=4; }
            else { wrong++; total -= 1; if(i<40) cs-=1; else if(i<63) math-=1; else reason-=1; }
        });
        document.getElementById("final-total").innerText = total; document.getElementById("score-cs").innerText = cs;
        document.getElementById("score-math").innerText = math; document.getElementById("score-reason").innerText = reason;
        document.getElementById("result-motive").innerText = quizData[activeSet].msg;
    }
    initHome();